In [4]:
from numpy import array, zeros
# Langkah 1 : inisialisasi matriks
A = array([[4., -2., 1., 3., -2.],
           [-1., 2., 3., -4., 5.],
           [1., -2., 4., -2., 1.],
           [5., -4., 4., 2., -1.],
           [-2., 3., 1., -2., 4.]])
print(A)
b = array([[1., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0.],
           [0., 0., 1., 0., 0.],
           [0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 1.]])
# Langkah 2 : memecah matriks b menjadi b1,b2 dan b3
n = len(A)
bl = zeros((n, 1))
# Langkah 3 : melakukan pengulangan
for w in range(n):
    for q in range(n):
        bl[q][0] = b[q][w]
A = array([[4., -2., 1., 3., -2.],
           [-1., 2., 3., -4., 5.],
           [1., -2., 4., -2., 1.],
           [5., -4., 4., 2., -1.],
           [-2., 3., 1., -2., 4.]])
# Langkah 4 : memulai matriks L
L = zeros((n, n))
for i in range(0, n):
    L[i][i] = 1
# proses triangularisasi
for k in range(0, n-1):
    # memulai pivot
    if A[k][k] == 0:
        for s in range(0, n):
            v = A[k][s]
            u = A[k+1][s]
            A[k][s] = u
            A[k+1][s] = v
# proses pivot selesai
    for j in range(k+1, n):
        m = A[j][k]/A[k][k]
        L[j][k] = m  # nilai m disimpan di matrik L
        for i in range(0, n):
            A[j][i] = A[j][i]-m*A[k][i]
# matriks L selesai
# Langkah 5 : memulai matriks U
U = zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        U[i][j] = A[i][j]
# matriks U selesai
# Langkah 6 : proses subtitusi maju (LY=B)
y = zeros((n, 1))
y[0][0] = bl[0][0]/L[0][0]
for j in range(1, n):
    S = 0
    for i in range(0, j):
        S = S+y[i][0]*L[j][i]
    y[j][0] = bl[j][0]-S
# Langkah 7 : proses subtitusi mundur (UX=Y)
x = zeros((1, n))
x[0][n-1] = y[n-1][0]/U[n-1][n-1]
for j in range(n-2, -1, -1):
    S = 0
    for i in range(j+1, n):
        S = S+U[j][i]*x[0][i]
    x[0][j] = (y[j][0]-S)/U[j][j]
# langkah 8 : mencetak nilai x
print(x)


[[ 4. -2.  1.  3. -2.]
 [-1.  2.  3. -4.  5.]
 [ 1. -2.  4. -2.  1.]
 [ 5. -4.  4.  2. -1.]
 [-2.  3.  1. -2.  4.]]
[[-0.55555556  0.33333333  0.66666667  0.66666667 -0.11111111]]
