In [10]:
from numpy import array, zeros
# Langkah 1 : inisialisasi matriks
A = array([[1., 2., 3.],
           [6., -8., 3.],
           [3., 4., 6.]])
y = array([[2.], [3.], [1.]])
print(A)
b = array([[1., 0., 0.],
           [0., 1., 0.],
           [0., 0., 1.]])
# Langkah 2 : memecah matriks b menjadi b1,b2 dan b3
n = len(A)
bl = zeros((n, 1))
# Langkah 3 : melakukan pengulangan
for w in range(n):
    for q in range(n):
        bl[q][0] = b[q][w]
# Langkah 4 : memulai matriks L
L = zeros((n, n))
for i in range(0, n):
    L[i][i] = 1
# proses triangularisasi
for k in range(0, n-1):
    # memulai pivot
    if A[k][k] == 0:
        for s in range(0, n):
            v = A[k][s]
            u = A[k+1][s]
            A[k][s] = u
            A[k+1][s] = v
# proses pivot selesai
    for j in range(k+1, n):
        m = A[j][k]/A[k][k]
        L[j][k] = m  # nilai m disimpan di matrik L
        for i in range(0, n):
            A[j][i] = A[j][i]-m*A[k][i]

print(L)
# matriks L selesai
# Langkah 5 : memulai matriks U
U = zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        U[i][j] = A[i][j]

print(U)
# matriks U selesai
# Langkah 6 : proses subtitusi maju (LY=B)

y[0][0]=bl[0][0]/L[0][0]
for j in range(1, n):
    S = 0
    for i in range(0, j):
        S = S+y[i][0]*L[j][i]
    y[j][0] = bl[j][0]-S
# Langkah 7 : proses subtitusi mundur (UX=Y)
x = zeros((1, n))
x[0][n-1] = y[n-1][0]/U[n-1][n-1]
for j in range(n-2, -1, -1):
    S = 0
    for i in range(j+1, n):
        S = S+U[j][i]*x[0][i]
    x[0][j] = (y[j][0]-S)/U[j][j]
# langkah 8 : mencetak nilai x
print(x)

[[ 1.  2.  3.]
 [ 6. -8.  3.]
 [ 3.  4.  6.]]
[[1.  0.  0. ]
 [6.  1.  0. ]
 [3.  0.1 1. ]]
[[  1.    2.    3. ]
 [  0.  -20.  -15. ]
 [  0.    0.   -1.5]]
[[ 1.          0.5        -0.66666667]]


In [9]:
from numpy import array, zeros
# Langkah 1 : inisialisasi matriks
A = array([[1., 2., 3., -1.],
           [2., 5., 4., 8.],
           [4., 2., 2., 1.],
           [6., 4., -1., -2.]])
y = array([[10.], [8.], [-2.], [4.]])
print(A)
b = array([[1., 0., 0., 0.],
           [0., 1., 0., 0.],
           [0., 0., 1., 0.],
           [0., 0., 0., 1.]])
# Langkah 2 : memecah matriks b menjadi b1,b2 dan b3
n = len(A)
bl = zeros((n, 1))
# Langkah 3 : melakukan pengulangan
for w in range(n):
    for q in range(n):
        bl[q][0] = b[q][w]
# Langkah 4 : memulai matriks L
L = zeros((n, n))
for i in range(0, n):
    L[i][i] = 1
# proses triangularisasi
for k in range(0, n-1):
    # memulai pivot
    if A[k][k] == 0:
        for s in range(0, n):
            v = A[k][s]
            u = A[k+1][s]
            A[k][s] = u
            A[k+1][s] = v
# proses pivot selesai
    for j in range(k+1, n):
        m = A[j][k]/A[k][k]
        L[j][k] = m  # nilai m disimpan di matrik L
        for i in range(0, n):
            A[j][i] = A[j][i]-m*A[k][i]

print(L)
# matriks L selesai
# Langkah 5 : memulai matriks U
U = zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        U[i][j] = A[i][j]

print(U)
# matriks U selesai
# Langkah 6 : proses subtitusi maju (LY=B)

y[0][0]=bl[0][0]/L[0][0]
for j in range(1, n):
    S = 0
    for i in range(0, j):
        S = S+y[i][0]*L[j][i]
    y[j][0] = bl[j][0]-S
# Langkah 7 : proses subtitusi mundur (UX=Y)
x = zeros((1, n))
x[0][n-1] = y[n-1][0]/U[n-1][n-1]
for j in range(n-2, -1, -1):
    S = 0
    for i in range(j+1, n):
        S = S+U[j][i]*x[0][i]
    x[0][j] = (y[j][0]-S)/U[j][j]
# langkah 8 : mencetak nilai x
print(x)


[[ 1.  2.  3. -1.]
 [ 2.  5.  4.  8.]
 [ 4.  2.  2.  1.]
 [ 6.  4. -1. -2.]]
[[ 1.          0.          0.          0.        ]
 [ 2.          1.          0.          0.        ]
 [ 4.         -6.          1.          0.        ]
 [ 6.         -8.          1.59090909  1.        ]]
[[  1.           2.           3.          -1.        ]
 [  0.           1.          -2.          10.        ]
 [  0.           0.         -22.          65.        ]
 [  0.           0.           0.         -19.40909091]]
[[-0.01639344  0.21077283 -0.15222482 -0.05152225]]
